version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Composer
  - package-ecosystem: "bundler"
    directory: "/darby/"
    schedule:
      interval: "daily"
