source "http://rubygems.org"

gem "activesupport"
gem "activemodel"
gem "alphavantagerb"
gem "daru-view", :git => "https://github.com/michaeldbianchi/daru-view"
gem "daru", git: "https://github.com/SciRuby/daru.git"
gem "global"
gem "rake"
gem 'retriable'
gem "zeitwerk"

group :development, :test do
  gem "pry-byebug"

  # iruby dependencies
  gem "ffi-rzmq"
  gem "iruby"
  gem "rbczmq"
end

group :test do
  gem "rspec"
end
