

namespace :darby do
  task :generate_analyzed_data do
    $:.unshift("lib")
    require "darby"
    Darby.generate_analyzed_data
  end

  task :clean_content_directory do
    $:.unshift("lib")
    require "darby"
     Darby.clean_content_directory
  end
end
