name: Secret Detector

on: [push]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    name: detects the secrets
    steps:
      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
