name: Secret Detector

on: [push]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    name: detects the secrets
    steps:
      - name: run detect secrets
        id: detect_secrets
        uses: evanextreme/detect-secrets-action@v1.0.0
